### ISSUE TITLE
Linux Support Meta Issue

### ISSUE THREAD

**Issue by Avasam** [Toufool/AutoSplit#224]
Until a first version with Linux support gets into master, this issue will serve to track progress, features, bugs, etc. concerning a Linux version. After that, everything left will be split in their own issues.

Ongoing PR to add Linux support: https://github.com/Toufool/AutoSplit/pull/153 . You can download dev builds from the GitHub Actions artefacts.

Must haves:
- [x] UI completely functional 
- [x] Basic hotkeys support (receive and send)
- [x] At least one X11 / X Server capture method
- [x] Works on debian-based distributions (Ubuntu, Pop!_OS, ...)
- [x] Usable performance
- [x] Retest everything after 2.0 update

Optional features:
- [x] Splash Screen
- [x] Application Icon
- [ ] Desktop Icon (https://github.com/Avasam/AutoSplit/issues/38)
    So as far as I understand it, Linux is dumb with icons and doesn't let you ship an icon as part of the file.
    So what if instead we just ran some variant of  `gio set ./AutoSplit.elf metadata::custom-icon file://./icon.ico` during boot? The icon will show up after first launch :)
    Here's a possible sensible location to extract the icon into:
    https://martin.hoppenheit.info/blog/2016/where-to-put-application-icons-on-linux/  
    https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-0.13.html#install_icons 
    `/usr/share/icons/hicolor/256x256/apps/AutoSplit.png`
- [ ] At least one Wayland compatible capture method (https://github.com/Avasam/AutoSplit/issues/39)
    None of our capture methods support Wayland atm.
    Possibly even our window position algorithms.
    This is not important. Wayland still need to mature a lot. Just keeping this here as a note.
- [ ] Decent performance (https://github.com/Avasam/AutoSplit/issues/44)
    Investigate SCROT performance (see https://github.com/asweigart/pyscreeze/issues/68)
    Also consider maim (same link)
    I'm fine having to use or make a fork.
- [ ] Account for rare window shadows (https://github.com/Avasam/AutoSplit/issues/42)
    Windows Shadows/Borders are a thing too on Linux (an easy example is Finder in Ubuntu/GNOME). It seems kinda rare that's actually an issue. Might be so specific to just the finder that it's not even something I should bother with? Time will tell if users encounter this. Very low priority until an issue actually arise.
- [ ] OBS Virtual Camera support (https://github.com/Avasam/AutoSplit/issues/41)
    My c920 webcam simply won't work (may or may not be a vmware issue).
    I can't get the virtual cam working in OBS.
    So I can't test or implement this feature myself 😕 (for all I know it's already working as-is).
- [ ] v4l2loopback Video Device support (https://github.com/Avasam/AutoSplit/issues/55)
- [ ] Multiple monitor support (https://github.com/Avasam/AutoSplit/issues/40)
    Linux in VMWare freaks out as soon as I try to have multiple monitors, the mouse and clicks locations are just way off. I'm not gonna attempts developing a solution in this state.
- [ ] Hotkeys support w/o having to be in special groups
- [ ] Numpad support (untested)
- [ ] Support hotkeys with modifiers (untested)
- [ ] Works on other distributions (untested)
- [x] Run in WSL2/WSLg without crashing (even if unusable)

Upstream any window manipulation improvements, bugfixes and new techniques to https://github.com/Kalmat/PyWinCtl

**Comment by Gamebuster19901** [comment]
Crash when a reset image is encountered:

Have to manually browse to reload splits when reset occurs.

```
Traceback (most recent call last):

  File "/home/gamebuster/Desktop/AutoSplit/scripts/../src/AutoSplit.py", line 580, in __auto_splitter
    if self.__similarity_threshold_loop(number_of_split_images, dummy_splits_array):

  File "/home/gamebuster/Desktop/AutoSplit/scripts/../src/AutoSplit.py", line 644, in __similarity_threshold_loop
    if self.__reset_if_should(capture):

  File "/home/gamebuster/Desktop/AutoSplit/scripts/../src/AutoSplit.py", line 835, in __reset_if_should
    return self.__check_for_reset_state_update_ui()

  File "/home/gamebuster/Desktop/AutoSplit/scripts/../src/AutoSplit.py", line 510, in __check_for_reset_state_update_ui
    self.gui_changes_on_reset(True)

  File "/home/gamebuster/Desktop/AutoSplit/scripts/../src/AutoSplit.py", line 782, in gui_changes_on_reset
    self.load_start_image_signal.emit(False, False)

TypeError: load_start_image_signal() only accepts 0 argument(s), 2 given!

```

**Comment by Gamebuster19901** [comment]
Yeah I just edited the file myself to remove the unused parameters.

**Comment by Avasam** [comment]
There's 3 unchecked boxes left, and Linux support is now a first-class citizen for AutoSplit, I'll unpin this issue.
If you're interested in Linux-specific issues: https://github.com/Toufool/AutoSplit/issues?q=sort%3Aupdated-desc+state%3Aopen+label%3A%22Linux%22
